### ISSUE TITLE
Asset manager create new asset from file does not seem to work

### ISSUE THREAD

**Issue by AddictArts** [adlnet/Sandbox#239] opened 2015-07-14 18:34 UTC
The documentation at http://sandboxdocs.readthedocs.org/en/latest/User%20Guide/Assets/ is out of date for the 1.0.0 beta. I attempted to upload a local COLLADA file, the dae, and uploading does nothing. I can select the dae and it the dialog shows that it is a COLLADA xml file mime type. Then clicking upload ends with a GET http request error. How is it supposed to work? Thanks

**Comment by rchadwic** [comment] 2015-07-14 19:41
Are you on a local server? I think we've found the issue: make sure you have some key in the config file for the "sessionSecret". The server will seem to run normally if this is lacking, but it cases issues with the asset server. Can you check this?

**Comment by stevenvergenz** [comment] 2015-07-14 19:56
Also note that the documentation refers to a different (and unrelated) upload system than that which is presented by Assets > Create New Asset > From File. The version in the documentation is now at Assets > 3DR > Upload Mesh To 3DR.

**Comment by AddictArts** [comment] 2015-07-14 20:04
@rchadwic thanks, checking that now.
@stevenvergenz is the documentation not going to be updated then? The experience I had is what anyone cloning and running it will see and the first thing a person is likely to try

**Comment by stevenvergenz** [comment] 2015-07-14 20:11
There's a tremendous documentation backlog right now, but yes, it's going to be updated eventually. In the meantime, we're trying to make it self-explanatory. I'll push a fix to this soon.

**Comment by rchadwic** [comment] 2015-07-14 20:15
You make a good point - we print a message "config file not found, loading defaults" but that default value is not moved into the asset server. This does require a fix.

**Comment by AddictArts** [comment] 2015-07-14 20:32
@rchadwic I tried adding a sessionSecret and it still fails.
![screen shot 2015-07-14 at 1 32 19 pm](https://cloud.githubusercontent.com/assets/911906/8684360/cd0df650-2a2c-11e5-8cc9-b3351c594475.png)

**Comment by AddictArts** [comment] 2015-07-14 20:33
This is my config
```json
{
    "sessionSecret": "a cookie secret",
    "branding": {
        "title":"SAVE",
        "logo":"",
        "tagline":"",
        "footer":"Semantic Assessment Virtual Environments"
    }
}
```

**Comment by stevenvergenz** [comment] 2015-07-14 20:53
Ah, that explains it then, if that's your entire config file. I recommend having all the same keys in your config file as [config.sample.json](https://github.com/adlnet/Sandbox/blob/master/config.sample.json). Technically the system will fill in the gaps with defaults, but it's not 100%. Try this for now, and I'll add some defaults to the asset server logic.

**Comment by AddictArts** [comment] 2015-07-14 21:55
Adding most of the fields from the sample fixed the issue. Although at first it was unclear what to do next after upload.

**Comment by AddictArts** [comment] 2015-07-15 01:07
My guess is the config hostAssets is the most important one. Textures are inconvenient after that though.

**Comment by stevenvergenz** [comment] 2015-07-15 12:22
How so? Just upload the textures as separate assets, and set them in a material.

**Comment by wilo1** [comment] 2015-07-15 17:53
Is there an example of a correct config file for the newer assets manager? I have successfully integrated an external instance of the 3DR, and also been able to successfully add local assets. But when trying to load the asset from external URL vs. local it won't work. It still thinks the assets are local.
Here is my config. Should something be in the remote asset server URL? I assumed that was for something different. I tried to use the app location but it still won't work.  
"hostAssets": true,
"remoteAssetServerURL": "",
    "assetDataDir": "assets",
	"assetSessionHeader": "X-Session-Cookie"

![local](https://cloud.githubusercontent.com/assets/6297072/8705588/98934a5c-2af8-11e5-91e1-a079600f2394.png)

**Comment by rchadwic** [comment] 2015-07-16 17:18
Can you explain a bit what you mean by "external url"?  Is this using the "Load mesh by URL" function, or some function in the asset server?

**Comment by wilo1** [comment] 2015-07-16 19:38
This occurs when creating a new asset from file. The 3DR implementation works to the external server just fine as does referencing an external hosting URL. It's when you try to add a new assest from file. It will only load to the local URL. I was assuming it would load to the same URL where the sandbox is hosted. But it will not work due to thinking it's a local host URL.
![newassest](https://cloud.githubusercontent.com/assets/6297072/8733204/96c4ea22-2bd0-11e5-90a1-fd3aa78b9bb4.png)

**Comment by stevenvergenz** [comment] 2015-07-16 20:12
Hmm, you are correct. I've reproduced this error on the live server, working to fix it now. Stand by.

**Comment by stevenvergenz** [comment] 2015-07-16 20:32
Something to try while I'm fixing this bug. When you have the asset selected in the assets manager, there should be a URL just under the Replace Asset box. Try copying that URL and pasting it as-is into the Assets > Load Mesh By URL dialog. Does that work?

**Comment by wilo1** [comment] 2015-07-16 20:39
Yes. That worked!

**Comment by stevenvergenz** [comment] 2015-07-16 20:51
So dragging/dropping from the library on the left is what produces your localhost error? If so, make sure that you're running the latest version of the Sandbox. That library bug should have been fixed as of ced5826.

**Comment by wilo1** [comment] 2015-07-17 12:06
Once I updated the repository it works. That was the issue. It's great to see this going now! Thanks!

**Comment by wilo1** [comment] 2015-07-17 14:19
Is there an asset refresh coming soon? Right now when you upload new models and textures into the integrated content library the only way to see them is to refresh the whole world. Or am I missing something?

**Comment by rchadwic** [comment] 2015-07-17 19:12
This is going to happen at some point, but unfortunately requires some non-trivial updates in the AssetManager. For now, you can still use a standalone 3DR for many of those use-cases. I know that the 3DR does not currently supported skinned mesh, so you're in a bit of a bind if you have a complex model that has animations and many textures...

You can also work around this by setting it up once and using the material editor on the loaded model, then save that whole thing as an entity.

**Comment by wilo1** [comment] 2015-07-17 19:30
The objective is to eventually have a method for students to contribute models and textures in easy way in collaborative worlds. The drag and drop is excellent. Just need a way for them to see everything because our students will be uploading a lot of objects they create themselves as part of a course. The 3DR is not really where we want them to upload but I will take a second look at how that would work. Using the asset manager is a 1000 times easier for kids. We are piloting our first elective this fall so we are trying to determine the best method that allows them to build their own library. I can tell you our students will love that.

**Comment by rchadwic** [comment] 2015-07-17 19:35
That sounds awesome! I'd love to see it working. So, if I understand Steve's code, you can upload textures, then drag and drop, no? It's just that you can't upload the model and textures together....

**Comment by wilo1** [comment] 2015-07-17 19:54
Yes and we can upload models  and texture and then drag them right in to the world. The issue is that once an asset is uploaded, be it a model or texture, it won't show up in the side panel under "my models' or 'my textures' automatically. I can see it now with our kids constantly whining about where they are... :=) You can see the newly loaded assets once the world is reloaded and or refreshed in the browser but that side panel is not refreshed after every upload in either chrome or IE.  It would also be nice to have some way to sort them all. I am just thinking ahead because I know how our students think and operate. I forsee the 'my models' and 'my textures' getting quite large and hard for them to organize.

**Comment by rchadwic** [comment] 2015-07-17 20:09
Ahhh this has a fairly easy fix. Open and close the library.

**Comment by wilo1** [comment] 2015-07-17 20:17
Wow. That worked. I feel stupid now. Thanks Robert. This is going to be wonderful for our students.

**Closed** 2015-07-22 19:59 UTC
