### ISSUE TITLE
Second copy of same uploaded model does not load into scene properly

### ISSUE THREAD

**Issue by AddictArts** [adlnet/Sandbox#246] opened 2015-07-18 00:42 UTC
What happens is the asset will be listed multiple times in the library my models sidebar. However, only one will work. I think it is the last one uploaded and the first in the last that you can add to the scene. The rest do nothing or error in the console.

**Comment by stevenvergenz** [comment] 2015-07-20 13:40
I haven't been able to reproduce this. Could you walk me through exactly what you're doing? My process:

1. logged in as the world owner
2. joined a world
3. uploaded a new DAE asset
4. uploaded the same DAE as a different asset
5. dragged the first model from the library into the scene
6. dragged the second model from the library into the scene

**Comment by AddictArts** [comment] 2015-07-22 22:29
Uploaded attached asset into two different worlds. You need to create one world, upload asset. Create another and then upload that same asset.
![two-assets-trunc-names](https://cloud.githubusercontent.com/assets/911906/8839013/69f4f0d6-3086-11e5-8a7e-3c35c2fea1bc.png)
![two-worlds](https://cloud.githubusercontent.com/assets/911906/8839015/70dd6702-3086-11e5-88fe-17cdd0d25d2f.png)
![m4_lowpoly_15 copy](https://cloud.githubusercontent.com/assets/911906/8839019/73b0c514-3086-11e5-8a01-5538b2ad2601.png)

**Comment by rchadwic** [comment] 2015-07-23 13:49
Ah, so, this turns out to be a bug in the EntityLibrary, which expects something to be unique that the asset server does not. Simple fix.

**Comment by rchadwic** [comment] 2015-07-23 15:10
Fixed in 0fd84e3

**Closed by rchadwic** 2015-07-23 15:10 UTC
